### ISSUE TITLE
attempt传入remember me时出错

### ISSUE THREAD

**Issue by czz1226** [nfangxu/hyperf-http-auth#1]
`$this->auth->attempt(['username' => $username, 'password' => $password], $remember)`
$remember为true时报错
`[ERROR] Cookie jar has not been set.[618] in /Volumes/Data/home/workspace/wwwroot/sys.test/src/vendor/fx/session-guard/src/SessionGuard.php
[ERROR] #0 /Volumes/Data/home/workspace/wwwroot/sys.test/src/vendor/fx/session-guard/src/SessionGuard.php(433): Fx\SessionGuard\SessionGuard->getCookieJar()`

**Comment by nfangxu** [comment]
问题已经定位了, 正在修复中...

**Comment by nfangxu** [comment]
更新到最新版本(v1.2)即可
