### ISSUE TITLE
require hyperf/cache version

### ISSUE THREAD

**Issue by cyskzl** [nfangxu/hyperf-http-auth#5]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for fx/hyperf-http-auth ^1.1 -> satisfiable by fx/hyperf-http-auth[1.x-dev, v1.1.1, v1.2].
    - Can only install one of: hyperf/cache[v2.0.0, 1.1.x-dev].
    - Can only install one of: hyperf/cache[1.1.x-dev, v2.0.0].
    - Can only install one of: hyperf/cache[1.1.x-dev, v2.0.0].
    - Conclusion: install hyperf/cache 1.1.x-dev
    - Installation request for hyperf/cache (locked at v2.0.0, required as ^2.0) -> satisfiable by hyperf/cache[v2.0.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by nfangxu** [comment]
你的hyperf用的是什么版本  

要是1.1.* 的版本用 1.* 的这个

2.0.* 的版本用 2.*

**Comment by cyskzl** [comment]
好的，谢谢
